import test from 'node:test';import assert from 'node:assert/strict';
import rules from '../content/levels/fire-shelter-practice/level.json';import skin from '../content/levels/fire-shelter-practice/skins/paper-gouache.json';
import {roomSmokeFrame,smokeRates,smokePoint,trainingRemaining} from '../app/game/runtime/room-smoke';
import {attachedBeam} from '../app/game/runtime/attached-beam';
import {validatePackage} from '../app/game/runtime/validate';import {createRun,reduceRun,findRule} from '../app/game/runtime/engine';import {scenePoses} from '../app/game/runtime/scene';import {presentationFrame} from '../app/game/runtime/presentation';import {PracticeCueTimeline,synthesiseCue} from '../app/game/runtime/practice-audio';
const pack=validatePackage(rules,skin),advance=(run:ReturnType<typeof createRun>,ms:number)=>{for(let t=0;t<ms;t+=20)run=reduceRun(pack,run,{type:'tick',ms:Math.min(20,ms-t)});return run;};
function apply(run:ReturnType<typeof createRun>,id:string){const r=pack.rules.interactions.find(r=>r.id===id)!;assert.equal(findRule(pack,run,r)?.id,id);return advance(reduceRun(pack,run,{type:'interact',input:r}),pack.skin.animations[r.animation].durationMs);}
const order=['close-room-door','block-door-gaps','reinforce-seal','contact-fire-service','shelter-family','signal-rescue'];
test('one towel and distinct tape; signal requires the actual flashlight drop',()=>{assert.equal(pack.rules.objects.filter(o=>o.label.includes('湿毛巾')).length,1);assert(!pack.rules.objects.some(o=>o.id==='sealing-cloth'));assert.equal(pack.skin.poses['sealing-tape'].asset,'tape-roll');assert.equal(pack.rules.objects.find(o=>o.id==='family')!.input,'drag');let run=createRun(pack);for(const id of order.slice(0,5))run=apply(run,id);assert.equal(findRule(pack,run,{source:'family',mode:'tap'}),undefined);assert.equal(findRule(pack,run,{source:'flashlight',mode:'drop',target:'family-signal'})?.id,'signal-rescue');run=apply(run,'signal-rescue');assert.equal(scenePoses(pack,run).find(p=>p.id==='flashlight')?.opacity,0);});
test('flashlight rays stay straight and rotate about the real lens with the actor',()=>{const b=pack.skin.presentation!.effects.find(e=>e.kind==='beam')!.beam!;let run=createRun(pack);for(const id of order)run=apply(run,id);for(const rotation of [-.08,0,.08]){const pose={...scenePoses(pack,run,true).find(p=>p.id==='family')!,rotation},ray=attachedBeam(pose,b);const midpoint={x:(ray.corners[1].x+ray.corners[2].x)/2,y:(ray.corners[1].y+ray.corners[2].y)/2};assert(Math.abs((midpoint.x-ray.origin.x)*ray.direction.y-(midpoint.y-ray.origin.y)*ray.direction.x)<1e-7);assert(Math.abs(Math.hypot(ray.end.x-ray.origin.x,ray.end.y-ray.origin.y)-b.length)<1e-7);assert(ray.direction.x<0&&ray.direction.y<0);}assert(!pack.skin.presentation!.effects.some(e=>e.kind==='light'&&e.when?.all?.includes('rescue-signalled')));});
test('six real goals, two people, no helper; both skins validate',()=>{assert.equal(pack.rules.goals.length,6);assert(!pack.rules.objects.some(o=>o.id==='door-helper'));assert(!pack.skin.poses['door-helper']);assert(!JSON.stringify(pack).includes('3人'));});
test('success waits for every goal and animation; no timeout death',()=>{let run=advance(createRun(pack),120000);assert.equal(run.phase,'playing');for(const id of order){const rule=pack.rules.interactions.find(r=>r.id===id)!;const start=reduceRun(pack,run,{type:'interact',input:rule});assert.deepEqual(start.resolved,run.resolved);assert.equal(reduceRun(pack,start,{type:'tick',ms:100,paused:true}),start);run=advance(start,pack.skin.animations[id].durationMs);}assert.equal(run.phase,'settling');assert.equal(advance(run,7199).phase,'settling');assert.equal(advance(run,7200).phase,'complete');});
for(const id of ['family-door-error','corridor-error','climb-out-error','reopen-door-error'])test(id+' is immediately fatal without rewards and can retry',()=>{let run=createRun(pack);if(id==='reopen-door-error')run=apply(run,'close-room-door');run=reduceRun(pack,run,{type:'interact',input:pack.rules.interactions.find(r=>r.id===id)!});assert.equal(run.phase,'failed');assert.equal(run.action,null);assert.equal(run.stars,0);assert.equal(advance(run,10000).phase,'failed');assert.equal(reduceRun(pack,run,{type:'reset'}).phase,'playing');});
test('50s countdown pauses, clamps to zero and still permits completion',()=>{let run=createRun(pack);assert.equal(pack.rules.risk.seconds,50);assert.equal(trainingRemaining(pack,run),50);run=advance(run,41000);assert.equal(trainingRemaining(pack,run),9);assert.equal(reduceRun(pack,run,{type:'tick',ms:100,paused:true}),run);run=advance(run,20000);assert.equal(trainingRemaining(pack,run),0);assert.equal(run.phase,'playing');for(const id of order)run=apply(run,id);assert.equal(run.phase,'settling');assert.equal(trainingRemaining(pack,advance(run,7200)),0);assert.deepEqual(reduceRun(pack,run,{type:'reset'}).resolvedAt,undefined);});
test('source flow stops while accumulated ceiling smoke stays continuous',()=>{let run=advance(createRun(pack),25000);const initial=roomSmokeFrame(pack,run)!;assert(initial.door===1&&initial.load>.5);run=apply(run,'close-room-door');const closed=roomSmokeFrame(pack,run)!;assert.equal(closed.door,0);assert(closed.gap>0);assert(closed.load>=initial.load);assert.equal(run.resolvedAt!['door-closed'],run.elapsed);assert.equal(smokeRates(closed.spec,run,run.elapsed-1).door,1);assert.equal(smokeRates(closed.spec,run,run.elapsed).door,0);run=apply(run,'block-door-gaps');const sealed=roomSmokeFrame(pack,run)!;assert(sealed.gap<closed.gap*.3);assert(sealed.load>=closed.load);run=apply(run,'reinforce-seal');assert(roomSmokeFrame(pack,run)!.load>=sealed.load);assert(roomSmokeFrame(pack,run)!.gap<sealed.gap);const towel=scenePoses(pack,run).find(p=>p.id==='wet-cloth')!;assert(towel.y<600&&towel.x>=474&&towel.x+towel.w<=620);let early=createRun(pack);for(const id of order.slice(0,3))early=apply(early,id);early=advance(early,25000-early.elapsed);assert(roomSmokeFrame(pack,early)!.load<initial.load*.5);const stream=initial.spec.door;assert(smokePoint(stream,.8).x<smokePoint(stream,.2).x);assert(smokePoint(stream,.8).y<smokePoint(stream,.2).y);});

test('actor cough state, gaze art and matching pose stay independent of logic',()=>{const run=advance(createRun(pack),6700),pose=scenePoses(pack,run).find(p=>p.id==='family')!;assert.equal(pose.asset,'family-cough');const still=scenePoses(pack,run,true).find(p=>p.id==='family')!;assert.equal(still.asset,'family-cough');assert.equal(still.rotation??0,0);assert.deepEqual(run.resolved,[]);});
test('alarm, heartbeat, cough, telephone, rescue have distinct non-speech PCM',()=>{const signatures=[];for(const id of ['fire-alarm','heartbeat','nonverbal-cough','telephone-connect','rescue-arrival']){const pcm=synthesiseCue(id);let energy=0,peak=0;for(const v of pcm){assert(Number.isFinite(v));energy+=v*v;peak=Math.max(peak,Math.abs(v));}assert(energy/pcm.length>.001);assert(peak<=.73);signatures.push(pcm.length+':'+energy.toFixed(5));}assert.equal(new Set(signatures).size,5);});
test('cues follow action clock, never repeat rescue, never reward failure',()=>{const t=new PracticeCueTimeline(pack);let run=createRun(pack);assert(t.advance(run).some(c=>c.id==='fire-alarm'));run=advance(run,6600);assert(t.advance(run).some(c=>c.id==='nonverbal-cough'));assert.equal(t.advance(run).length,0);for(const id of order){run=apply(run,id);t.advance(run);}run=advance(run,3200);assert(t.advance(run).some(c=>c.id==='rescue-arrival'));assert.equal(t.advance(run).length,0);t.reset();run=reduceRun(pack,createRun(pack),{type:'interact',input:pack.rules.interactions.find(r=>r.id==='corridor-error')!});assert(t.advance(run).some(c=>c.event==='failure'));assert.equal(t.advance(run).length,0);});
