// Generated by pnpm levels:sync. Do not edit by hand.
import { validatePackage } from '../runtime/validate';
import type { LevelPackage } from '../runtime/schema';
import rules0 from '../../../content/levels/flood-kit/level.json';
import skin0 from '../../../content/levels/flood-kit/skins/paperbook.json';
import rules1 from '../../../content/levels/clear-corridor/level.json';
import skin1 from '../../../content/levels/clear-corridor/skins/paperbook.json';
import rules2 from '../../../content/levels/lift-wait/level.json';
import skin2 from '../../../content/levels/lift-wait/skins/paperbook.json';
import rules3 from '../../../content/levels/well-call/level.json';
import skin3 from '../../../content/levels/well-call/skins/paperbook.json';
export const configuredPackages: LevelPackage[] = [
  validatePackage(rules0, skin0, { embedded: true }),
  validatePackage(rules1, skin1, { embedded: true }),
  validatePackage(rules2, skin2, { embedded: true }),
  validatePackage(rules3, skin3, { embedded: true }),
];
