// Generated by pnpm levels:sync. Do not edit by hand.
import { validatePackage } from '../runtime/validate';
import type { LevelPackage } from '../runtime/schema';

export const configuredPackages: LevelPackage[] = [

];
