// Generated by scripts/hunts.mjs sync. Do not hand-edit.
import p0_rules from '@/content/scenes/typhoon-home/rules.json';
import p0_skin from '@/content/scenes/typhoon-home/skin.json';
import p0_presentation from '@/content/scenes/typhoon-home/presentation.json';
import p1_rules from '@/content/scenes/charging-bedroom/rules.json';
import p1_skin from '@/content/scenes/charging-bedroom/skin.json';
import p1_presentation from '@/content/scenes/charging-bedroom/presentation.json';
import p2_rules from '@/content/scenes/bedroom-night-check-v2/rules.json';
import p2_skin from '@/content/scenes/bedroom-night-check-v2/skin.json';
import p2_presentation from '@/content/scenes/bedroom-night-check-v2/presentation.json';
import p2_performance from '@/content/scenes/bedroom-night-check-v2/performance.json';
import p3_rules from '@/content/scenes/kitchen-before-cooking-v2/rules.json';
import p3_skin from '@/content/scenes/kitchen-before-cooking-v2/skin.json';
import p3_presentation from '@/content/scenes/kitchen-before-cooking-v2/presentation.json';
import p3_performance from '@/content/scenes/kitchen-before-cooking-v2/performance.json';
import p4_rules from '@/content/scenes/clear-corridor-check-v2/rules.json';
import p4_skin from '@/content/scenes/clear-corridor-check-v2/skin.json';
import p4_presentation from '@/content/scenes/clear-corridor-check-v2/presentation.json';
import p4_performance from '@/content/scenes/clear-corridor-check-v2/performance.json';
import p5_rules from '@/content/scenes/quake-bedroom-v2/rules.json';
import p5_skin from '@/content/scenes/quake-bedroom-v2/skin.json';
import p5_presentation from '@/content/scenes/quake-bedroom-v2/presentation.json';
import p5_performance from '@/content/scenes/quake-bedroom-v2/performance.json';
import p6_rules from '@/content/scenes/storm-street-check-v2/rules.json';
import p6_skin from '@/content/scenes/storm-street-check-v2/skin.json';
import p6_presentation from '@/content/scenes/storm-street-check-v2/presentation.json';
import p6_performance from '@/content/scenes/storm-street-check-v2/performance.json';
import p7_rules from '@/content/scenes/thunder-park-v2/rules.json';
import p7_skin from '@/content/scenes/thunder-park-v2/skin.json';
import p7_presentation from '@/content/scenes/thunder-park-v2/presentation.json';
import p7_performance from '@/content/scenes/thunder-park-v2/performance.json';
import p8_rules from '@/content/scenes/forest-fire-sources-v2/rules.json';
import p8_skin from '@/content/scenes/forest-fire-sources-v2/skin.json';
import p8_presentation from '@/content/scenes/forest-fire-sources-v2/presentation.json';
import p8_performance from '@/content/scenes/forest-fire-sources-v2/performance.json';
export const generatedHuntPacks = [{rules:p0_rules,skin:p0_skin,presentation:p0_presentation},
{rules:p1_rules,skin:p1_skin,presentation:p1_presentation},
{rules:p2_rules,skin:p2_skin,presentation:p2_presentation,performance:p2_performance},
{rules:p3_rules,skin:p3_skin,presentation:p3_presentation,performance:p3_performance},
{rules:p4_rules,skin:p4_skin,presentation:p4_presentation,performance:p4_performance},
{rules:p5_rules,skin:p5_skin,presentation:p5_presentation,performance:p5_performance},
{rules:p6_rules,skin:p6_skin,presentation:p6_presentation,performance:p6_performance},
{rules:p7_rules,skin:p7_skin,presentation:p7_presentation,performance:p7_performance},
{rules:p8_rules,skin:p8_skin,presentation:p8_presentation,performance:p8_performance}];
